# Owl API error codes

# Auth errors
AUTH_NO_CLIENT = 101
AUTH_NO_TOKEN = 102
AUTH_WRONG_CREDENTIALS = 103

# Upload errors
UPLOAD_NO_FILE = 201
UPLOAD_WRONG_EXTENSION = 202
UPLOAD_WRONG_FILESIZE = 203

# Get errors
GET_EMPTY_REQUEST = 301
GET_FILENAME_INCORRECT = 302
GET_FILE_NOT_FOUND = 303

